name: muslim_data_flutter
description: >
  Best Muslim package that provides: 
  Prayer Times, Offline Geocoder, Names of Allah, and Azkars
version: 1.4.0
repository: https://github.com/kosratdev/muslim-data-flutter
issue_tracker: https://github.com/kosratdev/muslim-data-flutter/issues

topics:
  - muslim
  - prayer
  - prayer-times
  - azkar
  - names-of-allah

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.40
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.7.0

flutter:
  assets:
    - assets/db/
